name: hardware

on: [push, pull_request]

jobs:
  esp-prog-adapter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v0.9.0
      with:
        config: config.kibot.yaml
        dir: .
        schema: 'esp-prog-adapter.sch'
        board: 'esp-prog-adapter.kicad_pcb'

    - name: upload docs
      uses: actions/upload-artifact@v2
      with:
        name: esp-prog-adapter-docs
        path: output/docs/

    - name: upload PCBWay gerbers
      uses: actions/upload-artifact@v2
      with:
        name: esp-prog-adapter-pcbway
        path: output/gerbers/pcbway